### ISSUE TITLE
DB오류 예상 됨

### ISSUE THREAD

**Issue by djelalswns12** [Dynamic-LAB/sinsungo_server#8]
**DB오류**  

재료 id를 통해 재료 데이터의 수정삭제시 발생될거 같은 오류

**(다른 냉장고 데이터 접근오류)**

-기계1에서 냉장고1 정보를 받아오고 각 재료의 아이디 값을 가지고있음

-기계2에서 냉장고1로 접속하여 아이디 값 A를 가지는 재료를 삭제할 경우, DB에서 해당 아이템은 삭제됨

-삭제된 재료가 가장 마지막으로 추가된 재료라 가정하면 DB의 재료테이블에서 id테이블의 최대값은 A-1이 될것이고 오토인크리먼트에 의해 다음에 들어올 재료의 ID값은 A가 될 예정임

-기계3에서 냉장고2로 접속하여 재료를 추가했음, 추가된 재료의 id값은 A로 설정됨

-기계1에서 아이디값 A를 가지고 있는 재료를 삭제할 경우 냉장고2에서 생성된 재료가 삭제될것임.

**(멤버간 삭제 문제)**

-기계1에서 냉장고1 정보를 받아와서 재료정보를 가지고있음

-기계2에서 냉장고1로 접속하여 아이디 값 A를 가지는 재료를 삭제할 경우, DB에서 해당 아이템은 삭제됨

-삭제된 재료가 가장 마지막으로 추가된 재료라 가정하면 DB의 재료테이블에서 id필드의 최대값은 A-1이 될것이고 오토인크리먼트에 의해 다음에 들어올 재료의 ID값은 A가 될 예정임

-기계2에서 새로운 재료를 추가하면 해당 재료의 아이디는 A가 될것임

-기계1에서 아이디 A를 가진 재료를 삭제할 시 기계2에 의해  이미 삭제된 데이터임

-따라서 기계1에서 요청했던 id의 재료가 아닌 기계2에서 추가한 재료가 의도치 않게 삭제될것임

**생각해본 해결방안**
1)암호키 방안
- 냉장고재료테이블에 암호키 필드를 생성
- 어플에서 데이터 받아올때 재료별 암호키또한 가지고 있기
- 삭제 요청시 받아온 임호키 또한 id와 함께 보내기
- 해당 id와 암호키가 동일하면 재료 삭제 허용
- 만약 모두 비교하였는데 둘중 하나라도 거짓이면 데이터참조에 문제가 발생한것
- DB로부터 데이터 다시 받아와서 어플에 재렌더링

**Comment by jaeseuk** [comment]
auto_increment가 빈 값을 찾아서 넣어주는게 아니라 마지막 값을 가지고 있다가 그 값부터 증가시켜주기 때문에 수동으로 초기화 시켜주지 않는 이상 해당 오류는 발생하지 않을듯 함

**Comment by djelalswns12** [comment]
확인
